[system]
host = ":8080"
mode = "999"

[redis]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysql]
host = "127.0.0.1"
port = 3306
config = "charset=utf8mb4&parseTime=True&loc=Local"
db_name = "blog"
username = "root"
password = "123456"
max_idle_conns = 10
max_open_conns = 100
log_mode = "warn"
log_zap = true

[zap]
level = "debug" #debug info warn error dpanic panic fatal
format = "json"
prefix = ""
director = "log"
link_name = ""
show_line = true
encode_level = "LowercaseColorLevelEncoder"
stacktrace_key = "stacktrace"
log_in_console = true
max_size = 100
max_age = 7
max_backups = 7

[jwt]
signing_key = "puqiang"
expire_time = 86400
buffer_time = 86400